// <auto-generated />
namespace fragrance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createmenutable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createmenutable));
        
        string IMigrationMetadata.Id
        {
            get { return "202310171801231_create-menu-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
